# Main application configuration
app:
  name: flask-app
  replicas: 2
  image:
    repository: 761018866463.dkr.ecr.us-east-1.amazonaws.com/keretdodor/flask
    tag: "1.20250106161231"
  
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  
  probe:
    liveness:
      path: /health
      port: 8080
      initialDelaySeconds: 15
      periodSeconds: 20
  
  containerPort: 8080

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 8080

# Ingress configuration
ingress:
  enabled: true
  className: alb
  host: develeap.meltachot.site
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:761018866463:certificate/0b72b1c3-1571-49d7-ad5d-49ae4073c07c
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-port: '8080'
    alb.ingress.kubernetes.io/healthcheck-path: /

# ConfigMap configuration
configMap:
  name: app-config
  data:
    DB_HOST: mydb.c3k8uy80crux.us-east-1.rds.amazonaws.com
    DB_NAME: "mydb"
    BACKEND: "https://develeap.meltachot.site"

# Secret configuration
secret:
  name: db-credentials
  data:
    username: 
    password: 

# HPA configuration    
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilization: 70