apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  DB_HOST: {{ .Values.configMap.data.DB_HOST }}
  DB_NAME: {{ .Values.configMap.data.DB_NAME }}
  BACKEND: {{ .Values.configMap.data.BACKEND }}