apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-master-0
  namespace: dapr-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: gp2